export const ADD_STORY = 'ADD_STORY';
export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL';
export const UPLOAD_STORY = 'UPLOAD_STORY';
export const DETAILS_UPLOAD_COMPLETE = 'DETAILS_UPLOAD_COMPLETE';
export const IMAGE_UPLOAD_COMPLETE = 'IMAGE_UPLOAD_COMPLETE';
export const CONTENT_UPLOAD_COMPLETE = 'CONTENT_UPLOAD_COMPLETE';