export const ADD_STORY = 'ADD_STORY';
export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL';
export const UPLOAD_STORY = 'UPLOAD_STORY';
export const STORY_UPLOAD_COMPLETE = 'STORY_UPLOAD_COMPLETE';